[package]
name = "explora-engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "explora"
path = "src/main.rs"

[dependencies]
ash = "0.38"
ash-window = "0.13"
winit = "0.30"
glam.workspace = true
image = { version = "0.25", default-features = false, features = ["jpeg"] }
libloading = "0.8"
libc = "0.2"
airframe-format.workspace = true
sim.workspace = true
world.workspace = true

[build-dependencies]
airframe-baker.workspace = true
airframe-format.workspace = true
shaderc = "0.10.1"
world.workspace = true
