[package]
name = "explora-engine"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "explora"
path = "src/main.rs"

[dependencies]
ash = "0.38"
ash-window = "0.13"
winit = "0.30"
glam = "0.29"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
libloading = "0.8"
libc = "0.2"
airframe = { path = "../crates/airframe" }
sim = { path = "../crates/sim" }
world = { path = "../crates/world" }

[build-dependencies]
shaderc = "0.10.1"
world = { path = "../crates/world" }
