// Procedural glider airframe. Ported from the web prototype.
// Same planform, same parts, new storage: indexed triangles,
// one interleaved stream, baked flex weights, merged batches.
// Forward is +z here, so source z is negated and triangles flip.

/// Material category ID mapped to PBR albedo and emissive properties in the shader.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum MatId {
    /// Sail cloth weave with anisotropic texture filtering.
    Sail,
    /// Teal enamel over the composite fuselage shell.
    Composite,
    /// Dark structural carbon/graphite panels.
    Graphite,
    /// Brass structural fittings or steel rotor/nozzle parts, selected by node.
    Titanium,
    /// Matte black engine shroud, struts, and cockpit tub.
    Dark,
    /// Pilot seat cushion leather.
    Seat,
    /// Transparent canopy glass (drawn in alpha pass).
    Glass,
    /// Glowing engine exhaust and navigation lights.
    Glow,
}

/// Kinematic node hierarchy governing dynamic transformations (rigid animation and aeroelasticity).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Node {
    /// Main fuselage static frame.
    Hull,
    /// Cockpit canopy assembly.
    Canopy,
    /// Port (left) wing root.
    WingL,
    /// Starboard (right) wing root.
    WingR,
    /// Trailing-edge control flap (0..5).
    Flap(u8),
    /// Spinning jet turbine rotor hub.
    Rotor,
    /// Articulating thrust vectoring nozzle petal (0..9).
    Petal(u8),
    /// V-tail canted stabilizer fin (0..1).
    Fin(u8),
}

/// How soon a semantic part may leave the visual LOD chain.
///
/// The baker packs this into `PartDesc::flags` bits 8..12 and uses it to pick
/// per-level error budgets, RT proxy density, and task-shader screen-size
/// culling. Values match `airframe_format::IMPORTANCE_*`.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Importance {
    /// Planform outline that must survive longest: hull shell, sail, fins.
    Silhouette,
    /// Load-bearing surfaces that keep shape while still resolvable:
    /// flaps, booms, binding, nozzle petals, canopy frame.
    Structural,
    /// Small hardware that reads up close: bolts, struts, rotor blades,
    /// flap edge hardware.
    Detail,
    /// Geometry hidden behind or inside other surfaces: battens, stringers,
    /// exhaust liner, cockpit tub, seat.
    Interior,
    /// Emissive blobs that collapse to points first: nav glow, HUD, rotor glow.
    Emitter,
}

impl Importance {
    /// Stable wire value written into packed part flags.
    pub fn index(self) -> u32 {
        match self {
            Self::Silhouette => 0,
            Self::Structural => 1,
            Self::Detail => 2,
            Self::Interior => 3,
            Self::Emitter => 4,
        }
    }

    /// Absolute object-space chordal error budget in meters for offline
    /// primitive tessellation. Larger coarser geometry.
    pub fn tess_error(self) -> f32 {
        match self {
            Self::Silhouette => 0.001,
            Self::Structural => 0.005,
            Self::Detail => 0.012,
            Self::Interior => 0.025,
            Self::Emitter => 0.02,
        }
    }
}

/// Unindexed raw vertex generated by procedural CAD modeling functions.
pub struct RawVert {
    /// Position coordinates [x, y, z] in meters.
    pub pos: [f32; 3],
    /// Texture mapping coordinates [u, v].
    pub uv: [f32; 2],
    /// Aeroelastic flex influence weight along the wing span.
    pub flex: f32,
}

/// Discrete procedural airframe component before batching into merged GPU buffers.
pub struct RawPart {
    /// Kinematic node parent for animated motion.
    pub node: Node,
    /// Surface material identifier.
    pub mat: MatId,
    /// Semantic LOD/visibility class for the baker.
    pub importance: Importance,
    /// Vertex buffer payload.
    pub verts: Vec<RawVert>,
    /// Triangle index buffer.
    pub idx: Vec<u32>,
}
