// Procedural glider airframe. Ported from the web prototype.
// Same planform, same parts, new storage: indexed triangles,
// one interleaved stream, baked flex weights, merged batches.
// Forward is +z here, so source z is negated and triangles flip.

use glam::Vec3;

/// Material category ID mapped to PBR albedo and emissive properties in the shader.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum MatId {
    /// Sail cloth weave with anisotropic texture filtering.
    Sail,
    /// Teal enamel over the composite fuselage shell.
    Composite,
    /// Dark structural carbon/graphite panels.
    Graphite,
    /// Brass structural fittings or steel rotor/nozzle parts, selected by node.
    Titanium,
    /// Matte black engine shroud, struts, and cockpit tub.
    Dark,
    /// Pilot seat cushion leather.
    Seat,
    /// Transparent canopy glass (drawn in alpha pass).
    Glass,
    /// Glowing engine exhaust and navigation lights.
    Glow,
}

/// Kinematic node hierarchy governing dynamic transformations (rigid animation and aeroelasticity).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Node {
    /// Main fuselage static frame.
    Hull,
    /// Cockpit canopy assembly.
    Canopy,
    /// Port (left) wing root.
    WingL,
    /// Starboard (right) wing root.
    WingR,
    /// Trailing-edge control flap (0..5).
    Flap(u8),
    /// Spinning jet turbine rotor hub.
    Rotor,
    /// Articulating thrust vectoring nozzle petal (0..9).
    Petal(u8),
    /// V-tail canted stabilizer fin (0..1).
    Fin(u8),
}

/// Unindexed raw vertex generated by procedural CAD modeling functions.
pub struct RawVert {
    /// Position coordinates [x, y, z] in meters.
    pub pos: [f32; 3],
    /// Texture mapping coordinates [u, v].
    pub uv: [f32; 2],
    /// Aeroelastic flex influence weight along the wing span.
    pub flex: f32,
}

/// Discrete procedural airframe component before batching into merged GPU buffers.
pub struct RawPart {
    /// Kinematic node parent for animated motion.
    pub node: Node,
    /// Surface material identifier.
    pub mat: MatId,
    /// Vertex buffer payload.
    pub verts: Vec<RawVert>,
    /// Triangle index buffer.
    pub idx: Vec<u32>,
}

/// Convert IEEE 754 float32 to half-precision float16 bits with round-to-nearest-even.
pub fn f32_to_f16(v: f32) -> u16 {
    // Round-to-nearest-even fp32 to fp16 bits. No NaN payload care.
    let bits = v.to_bits();
    let sign = (bits >> 16) & 0x8000;
    let exp = ((bits >> 23) & 0xff) as i32 - 112;
    let mant = bits & 0x7fffff;
    if exp >= 31 {
        return (sign | 0x7bff) as u16;
    }
    if exp <= 0 {
        if exp < -10 {
            return sign as u16;
        }
        let shifted = (mant | 0x800000) >> (1 - exp) as u32;
        let half = (shifted + 0xfff + ((shifted >> 13) & 1)) >> 13;
        return (sign | half) as u16;
    }
    let half = (mant + 0xfff + ((mant >> 13) & 1)) >> 13;
    (sign | ((exp as u32) << 10) | half.min(0x3ff)) as u16
}

/// Encode a unit normal vector onto an octahedron mapped to 2x 16-bit signed normalized integers (SNORM16).
pub fn oct_encode(n: Vec3) -> [u16; 2] {
    // Octahedral normal map to SNORM16 pair.
    let l = n.x.abs() + n.y.abs() + n.z.abs();
    let mut x = n.x / l;
    let mut y = n.y / l;
    if n.z < 0.0 {
        let ox = x;
        x = (1.0 - y.abs()) * ox.signum();
        y = (1.0 - ox.abs()) * y.signum();
    }
    let enc = |v: f32| ((v.clamp(-1.0, 1.0) * 32767.0).round() as i32) as u16;
    [enc(x), enc(y)]
}

#[allow(dead_code)]
/// CPU-side twin of the shader decode. Kept for future picking.
pub fn oct_decode(pair: [u16; 2]) -> Vec3 {
    let dec = |v: u16| (v as i16) as f32 / 32767.0;
    let (x, y) = (dec(pair[0]), dec(pair[1]));
    let z = 1.0 - x.abs() - y.abs();
    let (mut nx, mut ny) = (x, y);
    if z < 0.0 {
        nx = (1.0 - y.abs()) * x.signum();
        ny = (1.0 - x.abs()) * y.signum();
    }
    Vec3::new(nx, ny, z).normalize_or_zero()
}

#[cfg(test)]
mod normal_tests {
    use super::*;

    #[test]
    fn octahedral_roundtrip_preserves_both_hemispheres() {
        for x in -8..=8 {
            for y in -8..=8 {
                for z in -8..=8 {
                    let v = Vec3::new(x as f32, y as f32, z as f32);
                    if v == Vec3::ZERO {
                        continue;
                    }
                    let n = v.normalize();
                    let decoded = oct_decode(oct_encode(n));
                    assert!((decoded - n).length() < 0.00015, "{n:?} -> {decoded:?}");
                }
            }
        }
    }
}
